spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:${JAWSDB_URL:mysql://localhost:3306/blogData?createDatabaseIfNotExist=true&serverTimezone=UTC&tinyInt1isBit=false}
spring.datasource.username: root
spring.datasource.password: password
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: none
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled: true
server.servlet.session.timeout: 60m
server.port: ${PORT:8080}

blog:
  title: DevPub
  subtitle: Блог начинающего разработчика
  phone: +7 (918) 789-45-54
  email: javajun@mail.ru
  copyright: Захарьев Эдуард
  copyrightFrom: 2017
  url: https://webblog-java.herokuapp.com

captcha.cleaning: 60

appEmail.email: no.reply.java.blog@gmail.com
appEmail.password: q43aRPLfXuvQ0rWszTTv

cloadinary.cloud_name: hxgzwz10h
cloadinary.api_key: 165699136286483
cloadinary.api_secret: 3Pw9DzhBsZ5hh8FaCB4AReHvMqg